@startuml

class FloorPlan {
    #length: double
    #width: double
    +getArea(): double
}

class Room {
    #length: double
    #width: double
    #height: double
    +getArea(): double
    +getVolume(): double
}

FloorPlan <|-- Room
@enduml